openapi: 3.0.2
info:
  title: movies_api
  version: 1.0.0
paths:
  /movies:
    summary: Path used to manage the list of movies.
    description: 'The REST endpoint/path used to list and create zero or more `Movie` entities. '
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movie'
          description: Successful response - returns an array of `Movie` entities.
      operationId: getMovies
      summary: List All Movies
      description: Gets a list of all `Movie` entities.
components:
  schemas:
    Movie:
      title: Root Type for Movie
      description: ''
      type: object
      properties:
        id:
          format: int32
          type: integer
        name:
          type: string
        rating:
          format: int32
          type: integer
        year:
          format: int32
          type: integer
        poster:
          type: string
      example:
        id: 1
        name: movie1
        rating: 3
        year: 2004
        poster: >-
          data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIAQMAAAD+wSzIAAAABlBMVEX///+/v7+jQ3Y5AAAADklEQVQI12P4AIX8EAgALgAD/aNpbtEAAAAASUVORK5CYII
  securitySchemes:
    Bearer:
      scheme: bearer
      type: http
