openapi: 3.0.2
info:
    title: movies_api
    version: 1.0.0
paths:
    /movies:
        summary: Path used to manage the list of movies.
        description: 'The REST endpoint/path used to list and create zero or more `Movie` entities. '
        get:
            requestBody: {}
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Movie'
                    description: Successful response - returns an array of `Movie` entities.
            operationId: getMovies
            summary: Get a list of every movie
            description: Gets a list of all `Movie` entities.
        post:
            requestBody:
                description: A new Movie to be created.
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Movie'
                        examples:
                            '204':
                                value:
                                    id: 1
                                    name: movie1
                                    rating: 3
                                    year: 2004
                                    poster: >-
                                        data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIAQMAAAD+wSzIAAAABlBMVEX///+/v7+jQ3Y5AAAADklEQVQI12P4AIX8EAgALgAD/aNpbtEAAAAASUVORK5CYII
                            '400':
                                value:
                                    id: 1
                                    name: ''
                                    rating: 3
                                    year: 2004
                                    poster: >-
                                        data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIAQMAAAD+wSzIAAAABlBMVEX///+/v7+jQ3Y5AAAADklEQVQI12P4AIX8EAgALgAD/aNpbtEAAAAASUVORK5CYII
                required: true
            responses:
                '201':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Movie'
                            examples:
                                '201':
                                    value:
                                        id: 1
                                        name: Movie 1
                                        image: >-
                                            data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIAQMAAAD+wSzIAAAABlBMVEX///+/v7+jQ3Y5AAAADklEQVQI12P4AIX8EAgALgAD/aNpbtEAAAAASUVORK5CYII
                    description: Successful response - Adds movie to the list of movies
                '400':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Movie'
                            examples:
                                '400':
                                    value:
                                        id: 1
                                        name: ''
                                        image: >-
                                            data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIAQMAAAD+wSzIAAAABlBMVEX///+/v7+jQ3Y5AAAADklEQVQI12P4AIX8EAgALgAD/aNpbtEAAAAASUVORK5CYII
                    description: When the user is admin but one or more params was incorrect or missing
                '401':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Movie'
                            examples:
                                '401':
                                    value:
                                        id: 1
                                        name: Movie 1
                                        image: >-
                                            data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIAQMAAAD+wSzIAAAABlBMVEX///+/v7+jQ3Y5AAAADklEQVQI12P4AIX8EAgALgAD/aNpbtEAAAAASUVORK5CYII
                    description: Will not add a movie to the list of movies because the user isn't logged in
                '403':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Movie'
                            examples:
                                '403':
                                    value:
                                        id: 1
                                        name: Movie 1
                                        image: >-
                                            data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIAQMAAAD+wSzIAAAABlBMVEX///+/v7+jQ3Y5AAAADklEQVQI12P4AIX8EAgALgAD/aNpbtEAAAAASUVORK5CYII
                    description: Will not add a movie to the list of movies because the user isnt an admin
            security:
                -
                    apiKey: []
            operationId: addMovie
            summary: Add a movie to the list
        delete:
            requestBody:
                content:
                    application/json:
                        schema:
                            type: array
                            items: {}
                        examples:
                            '204':
                                value:
                                    id: 1
                required: true
            responses:
                '204':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: integer
                            examples:
                                '204':
                                    value:
                                        id: 1
                    description: Successful response - removes the selected movie from the list
                '401':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: integer
                            examples:
                                '204':
                                    value:
                                        id: 1
                    description: Will not remove a movie from the list of movies because the user isn't logged in
                '403':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: integer
                            examples:
                                '204':
                                    value:
                                        id: 1
                    description: Will not remove a movie from the list of movies because the user isnt an admin
            security:
                -
                    apiKey: []
            operationId: deleteMovie
            summary: Remove a movie from the list
        patch:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Movie'
                        examples:
                            patch_204:
                                value:
                                    id: 1
                                    name: movie1
                                    rating: 3
                                    year: 2004
                                    poster: >-
                                        data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIAQMAAAD+wSzIAAAABlBMVEX///+/v7+jQ3Y5AAAADklEQVQI12P4AIX8EAgALgAD/aNpbtEAAAAASUVORK5CYII
                            patch_400:
                                value:
                                    id: 1
                                    name: ''
                                    rating: 3
                                    year: 2004
                                    poster: >-
                                        data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIAQMAAAD+wSzIAAAABlBMVEX///+/v7+jQ3Y5AAAADklEQVQI12P4AIX8EAgALgAD/aNpbtEAAAAASUVORK5CYII
                required: true
            responses:
                '204':
                    headers:
                        Authorization: {}
                    content:
                        application/json:
                            examples:
                                '204':
                                    value:
                                        id: 1
                                        name: movie1
                                        rating: 3
                                        year: 2004
                                        poster: >-
                                            data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIAQMAAAD+wSzIAAAABlBMVEX///+/v7+jQ3Y5AAAADklEQVQI12P4AIX8EAgALgAD/aNpbtEAAAAASUVORK5CYII
                    description: Successful response - Modifies a movie in the list of movies
                '400':
                    content:
                        application/json:
                            examples:
                                '400':
                                    value:
                                        id: 1
                                        name: ''
                                        rating: 3
                                        year: 2004
                                        poster: >-
                                            data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIAQMAAAD+wSzIAAAABlBMVEX///+/v7+jQ3Y5AAAADklEQVQI12P4AIX8EAgALgAD/aNpbtEAAAAASUVORK5CYII
                    description: When the user is admin and title WAS given but was EMPTY
                '401':
                    content:
                        application/json:
                            examples:
                                '401':
                                    value:
                                        id: 1
                                        name: movie1
                                        rating: 3
                                        year: 2004
                                        poster: >-
                                            data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIAQMAAAD+wSzIAAAABlBMVEX///+/v7+jQ3Y5AAAADklEQVQI12P4AIX8EAgALgAD/aNpbtEAAAAASUVORK5CYII
                    description: When the user was not logged in
                '403':
                    content:
                        application/json: {}
                    description: When the user was not admin
            security:
                -
                    apiKey: []
            operationId: editMovie
            summary: Edit movie info in the list
    /logs:
        get:
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                200_OK:
                                    value:
                                        -
                                            log_id: '1'
                                            timestamp: '2023-04-26 20:10:08'
                                            http_method: DELETE
                                        -
                                            log_id: '2'
                                            timestamp: '2023-04-27 13:44:27'
                                            http_method: DELETE
                    description: Successful response - returns an array of `Logs` entities.
            operationId: getLogs
            summary: Gets a list of logs affecting movies
            description: Gets a list of all `Logs` entities.
components:
    schemas:
        Movie:
            title: Root Type for Movie
            description: ''
            type: object
            properties:
                id:
                    format: int32
                    type: integer
                name:
                    type: string
                rating:
                    format: int32
                    type: integer
                year:
                    format: int32
                    type: integer
                poster:
                    type: string
            example:
                id: 1
                name: movie1
                rating: 3
                year: 2004
                poster: >-
                    data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIAQMAAAD+wSzIAAAABlBMVEX///+/v7+jQ3Y5AAAADklEQVQI12P4AIX8EAgALgAD/aNpbtEAAAAASUVORK5CYII
    securitySchemes:
        Bearer:
            scheme: bearer
            type: http
        apiKey:
            type: apiKey
            name: Authorization
            in: header
