openapi: 3.0.2
info:
    title: movies_api
    version: 1.0.0
paths:
    /movies:
        summary: Path used to manage the list of movies.
        description: 'The REST endpoint/path used to list and create zero or more `Movie` entities. '
        get:
            tags:
                - /movies
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Movie'
                    description: Successful response - returns an array of `Movie` entities.
            operationId: getMovies
            summary: List All Movies
            description: Gets a list of all `Movie` entities.
    /sessions:
        summary: Path used to manage the list of sessions.
        description: >-
            The REST endpoint/path used to list and create zero or more `Sessions` entities.  This path
            contains a `GET` and `POST` operation to perform the list and create tasks, respectively.
        post:
            requestBody:
                description: A new `Session` to be created.
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/User'
                required: true
            tags:
                - /sessions
            responses:
                '201':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Session'
                    description: Successful response.
                '400':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                            examples:
                                '400':
                                    value:
                                        error: One or all params are missing
                    description: One or all params are missing
                '401':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                            examples:
                                '401':
                                    value:
                                        error: 'Unauthorized: email or password is incorrect'
                    description: 'Unauthorized: email or password is incorrect'
            operationId: createSessions
            summary: Create a Session
            description: Creates a new instance of a `Session`.
components:
    schemas:
        Movie:
            title: Root Type for Movie
            description: ''
            type: object
            properties:
                id:
                    format: int32
                    type: integer
                name:
                    type: string
                rating:
                    format: int32
                    type: integer
                year:
                    format: int32
                    type: integer
                poster:
                    type: string
            example:
                id: 1
                name: movie1
                rating: 3
                year: 2004
                poster: >-
                    data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIAQMAAAD+wSzIAAAABlBMVEX///+/v7+jQ3Y5AAAADklEQVQI12P4AIX8EAgALgAD/aNpbtEAAAAASUVORK5CYII
        Session:
            title: Root Type for Session
            description: ''
            type: object
            properties:
                sessionId:
                    type: string
                isAdmin:
                    type: boolean
            example:
                sessionId: 91de5642-1acf-4a0d-994b-3991cabe1295
                isAdmin: true
        User:
            title: Root Type for User
            description: ''
            type: object
            properties:
                email:
                    type: string
                password:
                    type: string
            example:
                email: Admin
                password: Password
        Error:
            title: Root Type for Error
            description: ''
            type: object
            properties:
                error:
                    type: string
            example:
                error: One or all params are missing
    securitySchemes:
        Bearer:
            scheme: bearer
            type: http
